config/routes.rb
  # -*- encoding : utf-8 -*-

Lcmat::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. contact routes ===========================================================
  get "/contact" => "site#contact", as: :contact
  post "/contact" => "site#send_contact", as: :send_contact

#= 3. courses routes ===========================================================
  get '/cursos/:id' => 'courses#show', as: 'course'

#= 4. informatives routes ======================================================
  get '/informativos' => 'informatives#index', as: :informatives
  get '/informativo/:id' => 'informatives#show', as: :informative

#= 5. courses routes ===========================================================
  get '/professores/:id' => 'professors#show', as: 'professor'


  root :to => "site#index"
end

app/controllers/site_controller.rb
# -*- encoding : utf-8 -*-
class SiteController < ApplicationController

  def index
    @informatives = Informative.where('published = ?', true).order('updated_at DESC').limit(6)
    @home = Page.where('indicator = ?', Page::PAGES[:home]).first
  end

  # CONTACT BEGIN

  def contact
    @contact = Page.where('indicator = ?', Page::PAGES[:contact]).first
    @contact_form = Contact.new

    raise ActionController::RoutingError unless @contact.published
  end

  def send_contact
    @contact = Page.where('indicator = ?', Page::PAGES[:contact]).first
    @contact_form = Contact.new(params[:contact])

    if @contact_form.save
      redirect_to(contact_path, :notice => "Mensagem enviada com sucesso.")
    else
      render :action => :contact
    end
  end

  # CONTACT END
end

app/views/site/contact.html.erb
<%= content_for :content do %>

  <h1><%= @contact.title %></h1>

  <%= content_tag(:div, notice, class: 'alert alert-success') if notice %>

  <div class="contact_content">
    <%= @contact.content.html_safe %>
  </div>

  <div class="main well">
    <%= simple_form_for(@contact_form, url: send_contact_path, html: { class: 'form-horizontal' }) do |f| %>
        <%= f.input :name, required: false, input_html: { class: 'input-xxlarge'} %>
        <%= f.input :email, required: false, input_html: { class: 'input-xxlarge'} %>
        <%= f.input :message, as: :text, required: false, input_html: { class: 'input-xxlarge', rows: '10'} %>

        <div class="control-group">
          <div class="controls">
            <%= f.button :submit, 'Enviar mensagem', class: 'btn' %>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/site/index.html.erb
<%= content_for :content do %>

  <div class="header">
    <div class="jumbotron">
      <img src="/assets/logo.png"></img>
      <h1>LCMAT</h1>
      <p class="lead">Laboratório de Ciências Matemáticas da UENF</p>
    </div>
    <hr>
  </div>

  <% if @home.present? %>
    <div class="home_content">
      <%= @home.content.html_safe %>
    </div>
  <% end %>

  <% if @informatives.any? %>
    <hr>
    <h4 class="latest_informatives">Últimos informativos</h4>
    <div class="row-fluid">
      <div class="span6">
        <% [0, 2, 4].each do |i| %>
          <% informative = @informatives[i] %>
          <% if informative.present? %>
            <div class="informative_header">
              <div class="date">
                <p>
                  <span class="year"><%= informative.updated_at.year %></span>
                  <span class="month"><%= localize informative.updated_at, :format => '%b' %></span>
                  <span class="day"><%= informative.updated_at.day %></span>
                </p>
              </div>

              <div class="title">
                <h5><a href="<%= informative_path(informative) %>"><%= informative.title %> <i class="icon-share-alt"></i></a></h5>
                <p class="hour"><%= informative.updated_at.strftime('%H:%M') %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="span6">
        <% [1, 3, 5].each do |i| %>
          <% informative = @informatives[i] %>
          <% if informative.present? %>
            <div class="informative_header">
              <div class="date">
                <p>
                  <span class="year"><%= informative.updated_at.year %></span>
                  <span class="month"><%= localize informative.updated_at, :format => '%b' %></span>
                  <span class="day"><%= informative.updated_at.day %></span>
                </p>
              </div>

              <div class="title">
                <h5><a href="<%= informative_path(informative) %>"><%= informative.title %> <i class="icon-share-alt"></i></a></h5>
                <p class="hour"><%= informative.updated_at.strftime('%H:%M') %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <%= link_to 'Mais informativos', informatives_path, class: 'more_informatives' %>
    </div>
  <% end %>
<% end %>