config/routes.rb
  # -*- encoding : utf-8 -*-

Lcmat::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

#= 1. user routes ==============================================================
  devise_for :users

#= 2. contact routes ===========================================================
  get "/contact" => "site#contact", as: :contact
  post "/contact" => "site#send_contact", as: :send_contact

#= 3. courses routes ===========================================================
  get '/cursos/:id' => 'courses#show', as: 'course'

#= 4. informatives routes ======================================================
  get '/informativos' => 'informatives#index', as: :informatives
  get '/informativo/:id' => 'informatives#show', as: :informative

#= 5. courses routes ===========================================================
  get '/professores/:id' => 'professors#show', as: 'professor'


  root :to => "site#index"
end

app/views/layouts/_top_navbar.html.erb
<div class="navbar navbar-fixed-top main">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'LCMAT', root_path, class: 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
              Cursos
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu with-search">
              <li class="inverse">
                <form class="navbar-search pull-left" action="javascript:void(0)">
                  <input type="text" class="search-query" placeholder="Buscar">
                </form>
              </li>
              <% Course.all.each do |course| %>
                <li class="inverse"><%= link_to course.name, course %></li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
              Professores
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu with-thumb with-search">
              <li class="inverse">
                <form class="navbar-search pull-left" action="javascript: void(0);">
                  <input type="text" class="search-query" placeholder="Buscar">
                </form>
              </li>
              <% Professor.all.each do |professor| %>
                <li class="inverse">
                  <a href="<%= professor_path(professor) %>">
                    <%= image_tag professor.photo.url(:thumb), class: "img-polaroid" %>
                    <%= professor.name %>
                  </a>
                </li>
              <% end %>
            </ul>
          </li>
          <li><%= link_to "Informativos", informatives_path %></li>
          <li><%= link_to "Contato", contact_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="<%= configuration.keywords %>" name="keywords" />
    <meta content="<%= configuration.description %>" name="description" />
    <title><%= content_for?(:title) ? yield(:title) : "LCMAT" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <%= render 'layouts/top_navbar' %>

    <div class="container main_container">

      <%= yield :content %>

      <footer>
        <hr>
        <% if configuration.footer.present? %>
          <div class="footer_info">
            <%= simple_format h(configuration.footer) %>
          </div>
        <% end %>
      </footer>

    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="<%= configuration.keywords %>" name="keywords" />
    <meta content="<%= configuration.description %>" name="description" />
    <title><%= content_for?(:title) ? yield(:title) : "LCMAT" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>

<body>

  <%= render 'layouts/top_navbar' %>
  <div class="container singin_box">
    <%= yield :content %>
  </div>
</body>

</html>